service: notalock

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000

functions:
  api:
    handler: functions/server.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
